# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b49a3b4b9cefcb54bb0bfeff011682c2f3c576b1bee47814c1a18b2e36ccd32dda3916cf4535889f93b99e16ea45f4b140438f7509a292d993853a58918e0933

test:
  secret_key_base: da8e4435ab253c94b4caea53aa9d31bd3d4a266e30b71b933cfbca38eff0fb995432d2f95bfa490b277dd9394c3aecc7377ffdac565f0f633dfc598cca34dc3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
